module.exports = Object.assign(
  require('../data-sources/caselaw'),
  require('../data-sources/fcc-ecfs'),
  // require('../data-sources/gov-us-gsa-discovery-contracts'),
  // require('../data-sources/gov-us-gsa-discovery-vendors-activation'),
  // require('../data-sources/gov-us-gsa-discovery-vendors-expiration'),
  require('../data-sources/gov-us-we-the-people'),
  // require('../data-sources/nasa-jpl-fireball'),
  // require('../data-sources/nasa-neo'),
  require('../data-sources/nyc-311'),
  // require('../data-sources/nyc-311-dca'),
  // require('../data-sources/nyc-311-dca'),
  // require('../data-sources/nyc-311-dep'),
  // require('../data-sources/nyc-311-dhs'),
  // require('../data-sources/nyc-311-dob'),
  // require('../data-sources/nyc-311-doe'),
  // require('../data-sources/nyc-311-dof'),
  // require('../data-sources/nyc-311-dohmh'),
  // require('../data-sources/nyc-311-dot'),
  // require('../data-sources/nyc-311-dpr'),
  // require('../data-sources/nyc-311-dsny'),
  // require('../data-sources/nyc-311-edc'),
  // require('../data-sources/nyc-311-hpd'),
  // require('../data-sources/nyc-311-nypd'),
  // require('../data-sources/nyc-311-tlc'),
  require('../data-sources/open-corporates')
  // require('../data-sources/usgs-earthquakes')
)
